sudo: required
services:
  - docker

before_install:
  - docker build -t dmytrokyiashko/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run dmytrokyiashko/react-test npm run test -- --coverage

after_success:
  - docker build -t dmytrokyiashko/multi-client ./client
  - docker build -t dmytrokyiashko/multi-nginx ./nginx
  - docker build -t dmytrokyiashko/multi-server ./server
  - docker build -t dmytrokyiashko/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dmytrokyiashko/multi-client
  - docker push dmytrokyiashko/multi-nginx
  - docker push dmytrokyiashko/multi-server
  - docker push dmytrokyiashko/multi-worker
